### ISSUE TITLE
list and monitor commands in spatie/laravel-backup

### ISSUE THREAD

**Issue by avebers** [private-it/flysystem-google-drive#2]
Hey! Thanks for your package. I'm using it with [spatie/laravel-backup](https://github.com/spatie/laravel-backup). Backup is working well, but `list` and `monitor` commands are not seeing my backups, so because of that it's not cleaning old files as well.
Is there any workaround?
Thanks!

**Comment by Rendol** [comment]
This changes not tested (commit on branche develop).

For temporary use: `composer require private-it/flysystem-google-drive:dev-develop`

WIP
Laravel minimal version: 8.*
