### ISSUE TITLE
something is wrong with the git package of you?

### ISSUE THREAD

**Issue by torian257x** [private-it/flysystem-google-drive#3]
I deploy via git

and somehow your package was the only one I ever had problems with

did you commit it like a sub repo or link or something?

after manually deleting the .git and readding the files, it worked for me

**Comment by Rendol** [comment]
Hi, @Jossnaz!

Maybe your `autoload.php` not added path to package:
```
  "autoload": {
    "psr-4": {
      "PrivateIT\\FlySystem\\GoogleDrive\\": "src"
    }
  },
```

Please send me your Error message and stackTrace.

**Comment by torian257x** [comment]
@Rendol actually what really happened was that `/vendor/private-it/flysystem-google-drive/` was just a file instead of a folder, e.g. there was nothing inside of it. All other dependencies loaded correctly. But I cannot reproduce it now in an empty folder, so i will close
