### ISSUE TITLE
deleting files actually moves them to trash, is there a way to actually delete them completely?

### ISSUE THREAD

**Issue by torian257x** [private-it/flysystem-google-drive#4]
deleting files actually moves them to trash, is there a way to actually delete them completely?

**Comment by Rendol** [comment]
Hi, @Jossnaz !

This package is wrapper of nao-pon/flysystem-google-drive

In source "delete" exist move to trash:
https://github.com/nao-pon/flysystem-google-drive/blob/master/src/GoogleDriveAdapter.php#L339

But not found "emptyTrash"
https://developers.google.com/drive/api/v3/reference/files/emptyTrash

Pleas, send your question to:
https://github.com/nao-pon/flysystem-google-drive/issues
